apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monitoring-platform-service
  title: Monitoring Platform
  description: |
    A Grafana instance with Prometheus, Loki, Tempo.
  labels:
    tier: "2"
  links:
    - url: https://monitoring-platform.test
      title: Development URL
      icon: dashboard
  tags:
    - monitoring
    - telemetry
    - grafana
  annotations:
    github.com/project-slug: webgrip/monitoring-platform
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=monitoring-platform'
    backstage.io/code-coverage: enabled
spec:
  type: service
  owner: group:webgrip/infrastructure
  lifecycle: production
  system: monitoring-platform-system
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: telemetry-domain
  title: Telemetry
  description: |
    The telemetry domain is responsible for all things related to monitoring and observability.
    This includes Grafana dashboards.
spec:
  owner: group:webgrip/infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  title: Monitoring Platform
  name: monitoring-platform-system
  description: |
    The monitoring platform system is responsible for all things related to monitoring and observability.
    This includes Grafana dashboards.
spec:
  owner: group:webgrip/infrastructure
  domain: telemetry-domain