apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monitoring-platform-webhook-initializer
  namespace: webgrip
  title: Webhook Initializer
  description: |
    The Webhook Initializer service sets up webhooks for the monitoring platform.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: webgrip/webhook-initializer
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=webhook-initializer'
    simpleicons.org/icon-slug: githubactions
  tags:
    - monitoring
    - webhook
    - automation
  links:
    - url: https://github.com/webgrip/webhook-initializer
      title: Source Code
      icon: github
      type: source
spec:
  type: service
  lifecycle: development
  owner: group:webgrip/infrastructure
  system: monitoring-platform-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monitoring-platform-github-webhook-receiver
  namespace: webgrip
  title: GitHub Webhook Receiver
  description: |
    Receives and processes GitHub webhooks for the monitoring platform.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: webgrip/github-webhook-receiver
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=monitoring-platform-github-webhook-receiver'
    simpleicons.org/icon-slug: githubactions
  tags:
    - monitoring
    - github
    - webhook
  links:
    - url: https://github.com/webgrip/github-webhook-receiver
      title: Source Code
      icon: github
      type: source
spec:
  type: service
  lifecycle: development
  owner: group:webgrip/infrastructure
  system: monitoring-platform-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monitoring-platform-grafana-image-renderer
  namespace: webgrip
  title: Grafana Image Renderer
  description: |
    Grafana plugin for rendering panels and dashboards as images.
  labels:
    tier: "2"
  annotations:
    docker.io/image: grafana/grafana-image-renderer:3.11.0
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=monitoring-platform-grafana-image-renderer'
    simpleicons.org/icon-slug: grafana
  tags:
    - monitoring
    - grafana
    - rendering
  links:
    - url: https://github.com/grafana/grafana-image-renderer
      title: Source Code
      icon: github
      type: source
spec:
  type: library
  lifecycle: development
  owner: group:webgrip/infrastructure
  system: monitoring-platform-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monitoring-platform-ngrok
  namespace: webgrip
  title: Ngrok
  description: |
    Ngrok is used to expose the local webhook receiver to the internet for testing.
  labels:
    tier: "2"
  annotations:
    docker.io/image: ngrok/ngrok:3.10.0-alpine
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=monitoring-platform-ngrok'
    simpleicons.org/icon-slug: ngrok
  tags:
    - monitoring
    - ngrok
    - tunneling
  links:
    - url: https://ngrok.com/
      title: Ngrok Website
      icon: link
      type: website
    - title: Prometheus
      url: https://google.ch
      icon: prometheus
      type: website
    - title: Grafana
      url: https://google.ch
      icon: grafana
      type: website
    - title: Google BigQuery
      url: https://google.ch
      icon: googlebigquery
      type: website
    - title: 1.1.1.1
      url: https://google.ch
      icon: 1dot1dot1dot1
      type: website
    - title: Github copilot
      url: https://google.ch
      icon: githubcopilot
      type: website
    - title: Backstage
      url: https://google.ch
      icon: backstage
      type: website
spec:
  type: tool
  lifecycle: development
  owner: group:webgrip/infrastructure
  system: monitoring-platform-system
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: monitoring-platform-system
  namespace: webgrip
  title: Monitoring Platform
  description: |
    The monitoring platform system is responsible for all things related to monitoring and observability.
    This includes Grafana dashboards.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: webgrip/monitoring-platform
    backstage.io/techdocs-ref: dir:.
    simpleicons.org/icon-slug: grafana
  tags:
    - monitoring
    - telemetry
    - observability
    - grafana
    - logs
    - traces
  links:
    - url: https://monitoring-platform.test
      title: Development URL
      icon: dashboard
      type: website
spec:
  owner: group:webgrip/infrastructure
  domain: webgrip/telemetry-domain
  type: product
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monitoring-platform-grafana
  namespace: webgrip
  title: Grafana
  description: |
    Grafana is a multi-platform open source analytics and interactive visualization web application.
  labels:
    tier: "2"
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=monitoring-platform-grafana'
    simpleicons.org/icon-slug: grafana
  tags:
    - monitoring
    - telemetry
    - observability
    - grafana
  links:
    - url: https://monitoring-platform.test
      title: Development URL
      icon: dashboard
      type: website
spec:
  type: website
  lifecycle: experimental
  owner: group:webgrip/infrastructure
  system: monitoring-platform-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monitoring-platform-loki
  namespace: webgrip
  title: Loki
  description: |
    Loki is a horizontally-scalable, highly-available, multi-tenant log aggregation system inspired by Prometheus.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: grafana/loki
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=monitoring-platform-loki'
    simpleicons.org/icon-slug: grafana
  tags:
    - monitoring
    - telemetry
    - observability
    - logs
  links:
    - url: https://grafana.com/docs/loki/latest/
      title: Documentation
      icon: book
      type: website
spec:
  type: service
  lifecycle: experimental
  owner: group:webgrip/infrastructure
  system: monitoring-platform-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monitoring-platform-tempo
  namespace: webgrip
  title: Tempo
  description: |
    Tempo is an easy-to-operate, high-scale, and cost-effective distributed tracing system.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: grafana/tempo
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=monitoring-platform-tempo'
    simpleicons.org/icon-slug: grafana
  tags:
    - monitoring
    - telemetry
    - observability
    - traces
  links:
    - url: https://grafana.com/docs/tempo/latest/
      title: Documentation
      icon: book
      type: website
spec:
  type: service
  lifecycle: experimental
  owner: group:webgrip/infrastructure
  system: monitoring-platform-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monitoring-platform-otel-collector
  namespace: webgrip
  title: OpenTelemetry Collector (Contrib)
  description: |
    The OpenTelemetry Collector offers a vendor-agnostic implementation on how to receive, process and export telemetry data.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: open-telemetry/opentelemetry-collector-contrib
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=monitoring-platform-otel-collector'
    simpleicons.org/icon-slug: opentelemetry
  tags:
    - monitoring
    - telemetry
    - observability
    - collection
  links:
    - url: https://opentelemetry.io/
      title: Documentation
      icon: book
      type: website
spec:
  type: service
  lifecycle: experimental
  owner: group:webgrip/infrastructure
  system: monitoring-platform-system
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: monitoring-platform-mariadb
  namespace: webgrip
  title: MariaDB
  description: |
    MariaDB is a community-developed, commercially supported fork of the MySQL relational database management system.
  labels:
    tier: "3"
  annotations:
    github.com/project-slug: mariadb/server
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=monitoring-platform-mariadb'
    simpleicons.org/icon-slug: mariadb
  tags:
    - monitoring
    - telemetry
    - observability
  links:
    - url: https://mariadb.com/docs/server/
      title: Documentation
      icon: book
      type: website
spec:
  type: database
  owner: group:webgrip/infrastructure
  system: monitoring-platform-system
  lifecycle: experimental
