services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.52.0
    volumes:
      - ./src/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./src/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:11.0.0-ubuntu
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring-platform.entrypoints=http"
      - "traefik.http.routers.monitoring-platform.rule=Host(`monitoring-platform.test`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheaders.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.monitoring-platform.middlewares=traefik-https-redirect"
      - "traefik.http.routers.monitoring-platform-secure.entrypoints=https"
      - "traefik.http.routers.monitoring-platform-secure.rule=Host(`monitoring-platform.test`)"
      - "traefik.http.routers.monitoring-platform-secure.tls=true"
      - "traefik.http.routers.monitoring-platform-secure.tls.domains[0].main=monitoring-platform.test"
      - "traefik.http.routers.monitoring-platform-secure.tls.domains[0].sans=*.monitoring-platform.test"
      - "traefik.http.routers.monitoring-platform-secure.service=nginx-semver-actions"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./src/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./src/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./src/grafana/custom.ini:/etc/grafana/custom.ini

  loki:
    container_name: loki
    image: grafana/loki:2.9.8
    ports:
      - "3100:3100"
    volumes:
      - ./src/loki:/etc/loki
      - ./src/loki/wal:/wal
      - ./src/loki/chunks:/chunks
      - ./src/loki/index:/index
      - ./src/loki/local-config.yaml:/etc/loki/local-config.yaml
    environment:
      - LOKI_STORAGE_PATH=/wal
      - LOKI_CHUNKS_PATH=/chunks
      - LOKI_INDEX_PATH=/index

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:v1.8.1
    ports:
      - "9100:9100"

  github-webhook-receiver:
    container_name: github-webhook-receiver
    build:
      context: src/github-webhook-receiver
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVICE_PUBLIC_URL=http://ngrok:4040

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:3.10.0-alpine
    #restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./src/ngrok/ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    env_file:
      -  src/ngrok/.env

  mariadb:
    container_name: mariadb
    build:
      context: ./src/mariadb
      dockerfile: Dockerfile
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitor
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitor

volumes:
  grafana-data:

networks:
  default:
    external: true
    name: magento
