services:

  mariadb:
    container_name: mariadb
    build:
      context: ./src/mariadb
      dockerfile: Dockerfile
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitor
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitor

networks:
  default:
    external: true
    name: magento
