services:
  webhook-initializer:
    container_name: webhook-initializer
    build:
      context: ops/webhook-initializer
      dockerfile: Dockerfile
    env_file:
      - ops/webhook-initializer/.env

networks:
  default:
    external: true
    name: webgrip