site_name: 'Monitoring Platform Docs'

theme:
  name: 'material'

nav:
  - Home: index.md
  - Architecture: architecture.md

plugins:
  - techdocs-core
  - macros
  - mermaid2:
      arguments:
        securityLevel: 'loose'

markdown_extensions:
  - markdown_inline_mermaid
