namespace: backend

deployment:
  strategy:
    type: RollingUpdate

replicaCount: 1

image:
  repository: webgrip/monitoring-platform-grafana
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "200m"
    memory: "100Mi"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  host: monitoring-platform.k8s.traefik.webgrip.nl
  annotations:
    cert-manager.io/issuer: letsencrypt-traefik
  tls:
    enabled: true
    secretName: letsencrypt-traefik-grafana
  paths:
    - path: /
      pathType: Prefix
      port: 80

#readinessProbe:
#  path: /readyz
#  initialDelaySeconds: 5
#  periodSeconds: 10
#
#livenessProbe:
#  path: /healthz
#  initialDelaySeconds: 10
#  periodSeconds: 20
