namespace: monitoring

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
      type: LoadBalancer
      port: 80
  ingress:
      enabled: true
      annotations:
      kubernetes.io/ingress.class: nginx
      hosts:
      - host: grafana.{{ .Values.namespace }}.{{ .Values.clusterDomain }}
          paths:
