{
 "title": "Client Environment Dashboard",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m, 5m, 10m, 30m, 1h, 6h, 12h, 24h"
   },
   {
    "name": "client",
    "label": "Client",
    "query": "SELECT DISTINCT Customer FROM your_table_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Client Environment Overview",
   "type": "table",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 10 },
   "targets": [
    {
     "rawSql": "SELECT `Github URL`, `Customer`, `Environment`, `Hostname`, `User`, `Port`, `Branch`, `Base URL`, `Admin URL`, `Themes`, `Languages`, `HaProxy`, `Apache`, `Varnish`, `Elasticsearch`, `ImgProxy`, `RedisCache`, `RedisSession`, `MySQL`, `PHP`, `Varnish image cache`, `Metapackage version`, `composer vendic imgproxy version`, `Sites`, `Allowed sources`, `Allowed dev sources` FROM your_table_name"
    }
   ]
  },
  {
   "title": "PHP Version Distribution",
   "type": "graph",
   "gridPos": { "x": 0, "y": 10, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT time, version FROM php_versions WHERE $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Apache Version Distribution",
   "type": "graph",
   "gridPos": { "x": 12, "y": 10, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT time, version FROM apache_versions WHERE $__timeFilter(time)"
    }
   ]
  }
 ]
}