namespace: monitoring

opentelemetry-collector:
  mode: deployment

  image:
    repository: "otel/opentelemetry-collector-contrib"

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

#  image:
#    repository: otel/otel-
#    pullPolicy: IfNotPresent
#    tag: latest

#  command:
#    name: otelcol
#    args:
#      - "--config=/etc/otel-collector-config.yaml"

#  service:
#    type: ClusterIP

#  config:
#    receivers:
#      otlp:
#        protocols:
#          grpc:
#            endpoint: 0.0.0.0:4317
#          http:
#            endpoint: 0.0.0.0:4318
#    processors:
#      batch: {}
#    exporters:
#      debug:
#        verbosity: normal
#      otlphttp:
#        endpoint: http://monitoring-platform-loki:3100/otlp
#        tls:
#          insecure: true
#      otlp/tempo:
#        endpoint: http://monitoring-platform-tempo:4317
#        tls:
#          insecure: true
#      prometheus:
#        endpoint: "0.0.0.0:8889"
#        const_labels:
#          label1: value1
#    extensions:
#      health_check:
#        endpoint: "0.0.0.0:13133"
#      pprof: {}
#      zpages: {}
#    service:
#      extensions: [health_check, pprof, zpages]
#      pipelines:
#        logs:
#          exporters:
#            - debug
#          processors:
#            - memory_limiter
#            - batch
#          receivers:
#            - otlp
#        metrics:
#          exporters:
#            - debug
#          processors:
#            - memory_limiter
#            - batch
#          receivers:
#            - otlp
#            - prometheus
#        traces:
#          exporters:
#            - debug
#          processors:
#            - memory_limiter
#            - batch
#          receivers:
#            - otlp
#            - jaeger
#            - zipkin
#      pipelines:
#        logs:
#          exporters: [ debug ]
#          processors:
#          receivers: [ otlp ]
#        traces:
#          receivers: [otlp]
#          processors: [batch]
#          exporters: [debug, otlp/tempo]
#        metrics:
#          receivers: [otlp]
#          processors: [batch]
#          exporters: [debug, prometheus]

#  ports:
#    otlp:
#      enabled: true
#      containerPort: 4317
#      servicePort: 4317
#      protocol: TCP
#    otlp-http:
#      enabled: true
#      containerPort: 4318
#      servicePort: 4318
#      protocol: TCP
#    health_check:
#      enabled: true
#      containerPort: 13133
#      servicePort: 13133
#      protocol: TCP

#  alternateConfig: |
#    receivers:
#      otlp:
#        protocols:
#          grpc:
#            endpoint:
