C4Context
    title System Context diagram for monitoring-platform

    Person(userA, "User", "Developer wanting to look at the monitoring platform")
    Rel(userA, SystemGrafana, "Uses")

    System_Boundary(BoundaryDevelopment, "Development of a new application") {
        System_Boundary(BoundaryApplication, "Actual app") {
            System(SystemApplication, "System", "https://new-application.test", "HTTPS")
            System(SystemApplicationBackgroundSystem, "Background System")
            BiRel(SystemApplication, SystemApplicationBackgroundSystem, "Sends data to")

            Rel(SystemApplication, DevelopmentOpenTelemetryCollector, "Sends data to")
            Rel(SystemApplicationBackgroundSystem, DevelopmentOpenTelemetryCollector, "Sends data to")
        }

        System_Boundary(BoundaryDevelopmentExternal, "External stuff") {
            System_Ext(ExternalSystemMkCert, "MkCert", "Creates and stores certificate for local SSL")
            Rel(ExternalSystemMkCert, SystemApplication, "Creates certificates for")

            System(DevelopmentOpenTelemetryCollector, "Open Telemetry Collector", "monitoring-platform-otel-collector:4317", "All the telemetry of monitoring-platform (The application) is sent here.")
            Rel(DevelopmentOpenTelemetryCollector, SystemTempo, "Sends traces to")
            Rel(DevelopmentOpenTelemetryCollector, SystemLoki, "Sends logs to")
        }



    }

    System_Boundary(BoundaryMonitoringPlatform, "Monitoring platform") {
        System_Boundary(BoundaryFrontEnd, "UI") {
            System(SystemGrafana, "Grafana", "https://monitoring-platform.test", "HTTPS")
            Rel(SystemGrafana, SystemLoki, "Reads from")
            Rel(SystemGrafana, SystemTempo, "Reads from")
            Rel(SystemGrafana, SystemMariaDb, "Reads from")
        }

        System_Boundary(BoundaryBackEnd, "BackEnd") {
            System(SystemGrafanaImageRenderer, "Grafana Image Rendereer", "http://grafana-image-renderer:8081", "HTTP")
            Rel(SystemGrafanaImageRenderer, SystemGrafana, "Renders images for")
        }


        System_Boundary(BoundaryBackEnd, "BackEnd") {
            System(SystemGrafanaImageRenderer, "Grafana Image Rendereer", "http://grafana-image-renderer:8081", "HTTP")
            Rel(SystemGrafanaImageRenderer, SystemGrafana, "Renders images for")
        }

        System_Boundary(BoundaryPersistence, "Persistence") {
            System(SystemLoki, "Loki", "monitoring-platform-loki:3100")
            System(SystemTempo, "Tempo", "monitoring-platform-tempo:3200")
            SystemDb(SystemMariaDb, "MariaDB", "monitoring-platform-mariadb:3306")
        }
        System_Boundary(BoundaryExternal, "External stuff") {
            System_Ext(SystemMkCert, "MkCert", "Creates and stores certificate for local SSL")
            Rel(SystemMkCert, SystemGrafana, "Creates certificates for")
            System(SystemOpenTelemetryCollector, "Open Telemetry Collector", "monitoring-platform-otel-collector:4317", "All the telemetry of monitoring-platform (The application) is sent here.")
            Rel(SystemOpenTelemetryCollector, SystemTempo, "Sends telemetry data to")
        }



        System_Boundary(BoundaryTests, "Testing") {
            System(SystemK6, "K6", "monitoring-platform-k6-tracing")
            Rel(SystemK6, SystemOpenTelemetryCollector, "Sends telemetry data to")
        }
    }

    UpdateLayoutConfig($c4ShapeInRow="1", $c4BoundaryInRow="2")