on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        description: 'DockerHub username'
        required: true
      DOCKER_TOKEN:
        description: 'DockerHub token'
        required: true

jobs:
  build-docker-image-monitoring-platform-grafana:
    name: 'Build Grafana'
    runs-on: self-hosted
    environment: ${{ inputs.github-environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ops/grafana
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            webgrip/monitoring-platform-grafana:latest
            webgrip/monitoring-platform-grafana:${{ github.sha }}

  build-docker-image-monitoring-platform-loki:
    name: 'Build Loki'
    runs-on: self-hosted
    environment: ${{ inputs.github-environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ops/otel-collector
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            webgrip/monitoring-platform-otel-collector:latest
            webgrip/monitoring-platform-otel-collector:${{ github.sha }}
