concurrency:
  group: push-${{ github.branch }}

on:
  push:
    branches:
      - 'master'
      - 'main'
    paths:
      - 'ops/**'
      - '.github/workflows/on_source_change.yml'
      - '.github/workflows/docker_build_and_push.yml'
jobs:
  build:
    uses: ./.github/workflows/docker_build_and_push.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
